[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

[dependencies]

log="*"
env_logger="*"

gtk = { version="*", package="gtk4", features=["v4_14"] }
glib-macros = "*"
rfd = "*"

once_cell = "*"

[build-dependencies]
glib-build-tools = "*"